//Service state actions
export const LOAD_STATE_REQUEST = 'LOAD_STATE_REQUEST'
export const LOAD_STATE_RECEIVE = 'LOAD_STATE_RECEIVE'
export const LOAD_STATE_ERROR = 'LOAD_STATE_ERROR'

//Sports actions
export const ADD_SPORT = 'ADD_SPORT'
export const REMOVE_SPORT = 'REMOVE_SPORT'
export const ADD_SPORT_HAHSES = 'ADD_SPORT_HAHSES'
export const REMOVE_SPORT_HASHES = 'REMOVE_SPORT_HASHES'
export const LOAD_SPORT_HASHES = 'LOAD_SPORT_HASHES'

//Service contact actions
export const LOAD_CONTACTS_REQUEST = 'LOAD_CONTACTS_REQUEST'
export const LOAD_CONTACTS_RECEIVE = 'LOAD_CONTACTS_RECEIVE'
export const LOAD_CONTACTS_ERROR = 'LOAD_CONTACTS_RECEIVE'
export const UPDATE_CONTACT = 'UPDATE_CONTACT'

//Service data actions
export const LOAD_SERVICE_DATA_REQUEST = 'LOAD_SERVICE_DATA_REQUEST'
export const LOAD_SERVICE_DATA_RECEIVE = 'LOAD_SERVICE_DATA_RECEIVE'
